Repository WildCodeSchool/orleans-php-202103-project-javoy, pull requests merged in 2021-04, with the labels that each got.

#17 initialisation
  public/assets/css/style.css
  src/View/Home/index.html.twig
  src/View/layout.html.twig
Labels: Changes requested, Corrections done, Reviewed

#21 S01 us12 header
  public/assets/css/header.css
  public/assets/css/style.css
  public/assets/images/bg_header.jpg
  public/assets/images/logo.png
  public/assets/images/panier.png
  src/View/Home/index.html.twig
  src/View/includes/_navbar.html.twig
  src/View/layout.html.twig
Labels: Corrections done, Reviewed

#18 HTML form ajout de produit Admin
  JavoyDb.sql
  public/assets/css/style.css
  simple-mvc.sql
  src/Controller/AdminProductController.php
  src/Model/ProductManager.php
  src/View/Admin/_adminProductsForm.html.twig
  src/View/Admin/add.html.twig
Labels: Corrections done, Reviewed

#29 create admin navbar
  public/assets/css/adminStyle .css
  src/View/Admin/_adminNavbar.html.twig
  src/View/Admin/add.html.twig
  src/View/adminLayout.html.twig
Labels: Corrections done, Reviewed

#30 S01 us01 fix
  public/assets/css/add-products.css
  public/assets/css/style.css
  src/Model/ItemManager copy.php
  src/View/Admin/add.html.twig
  src/View/Item/_adminForm.html.twig
Labels: Corrections done, Reviewed

#57 S02 us06 footer
  public/assets/css/adminStyle .css
  public/assets/css/footer.css
  public/assets/css/style.css
  public/assets/images/logo.png
  public/assets/images/logo.svg
  public/assets/images/logoBAF.svg
  public/assets/images/logoFB.svg
  public/assets/images/logoVI.svg
  src/Model/ItemManager.php
  src/View/Admin/add.html.twig
  src/View/Item/_adminForm.html.twig
  src/View/adminLayout.html.twig
  src/View/includes/_footer.html.twig
  src/View/layout.html.twig
Labels: Corrections done, Reviewed

#65 Creation page edit
  src/Controller/AdminProductController.php
  src/Model/ProductManager.php
  src/View/Admin/edit.html.twig
Labels: Corrections done, Reviewed

#66 Creation d'un fichier pour afficher les récompenses
  public/assets/css/recompense.css
  src/View/includes/_recompense.html.twig
Labels: Reviewed

#72 S02 us01 section histoire
  public/assets/css/history.css
  public/assets/images/first_savoir.jpeg
  public/assets/images/grape.jpg
  public/assets/images/history.jpeg
  public/assets/images/history1.jpeg
  public/assets/images/history2.jpg
  public/assets/images/second_savoir.jpeg
  public/assets/images/third_savoir.jpg
  src/View/Home/index.html.twig
  src/View/includes/_history.html.twig
Labels: Reviewed

#81 merge history to master
  public/assets/css/history.css
  public/assets/images/first_savoir.jpeg
  public/assets/images/grape.jpg
  public/assets/images/history.jpeg
  public/assets/images/history1.jpeg
  public/assets/images/history2.jpg
  public/assets/images/second_savoir.jpeg
  public/assets/images/third_savoir.jpg
  src/View/Home/index.html.twig
  src/View/includes/_history.html.twig
Labels: Reviewed

#79 changement products en product
  src/Controller/AdminProductController.php
  src/Model/ProductManager.php
  src/View/Admin/_adminProductsForm.html.twig
  src/View/Admin/add.html.twig
Labels: Reviewed

#80 Changement products en products dans la methode update de ProductManager
  src/Model/ProductManager.php
Labels: Reviewed

#84 Dev To master, S02
  src/Controller/AdminProductController.php
  src/Model/ProductManager.php
  src/View/Admin/_adminProductsForm.html.twig
  src/View/Admin/add.html.twig
Labels: Reviewed

#82 corrections de 2 fichiers
  public/assets/css/category.css
  public/assets/css/style.css
  public/assets/images/vignes.jpg
  src/Controller/CategoryController.php
  src/Model/CategoryManager.php
  src/View/Category/index.html.twig
Labels: Need Review, Reviewed

#83 Fix ajout des images de récompense
  public/assets/images/coup-de-coeur-guide-hachette-scaled.jpg
  public/assets/images/medaille-argent.png
  public/assets/images/medaille-or.png
  src/View/includes/_recompense.html.twig
Labels: Reviewed

#103 Add files via upload
  public/assets/images/logo.png
Labels: Reviewed

#70 S02 us09 creation formulaire commande
  .gitignore
  JavoyDb.sql
  config/db.php.dist
  public/assets/css/add-products.css
  public/assets/css/style.css
  src/Controller/OrderController.php
  src/Model/OrderManager.php
  src/View/Item/index.html.twig
  src/View/Order/add.html.twig
  src/View/Order/thanks.html.twig
  src/View/includes/_navbar.html.twig
  src/View/includes/_orderForm.html.twig
Labels: Corrections done, Reviewed

#116 fix relation de _recompense à home/index
  public/assets/css/recompense.css
  src/View/Home/index.html.twig
  src/View/includes/_recompense.html.twig
Labels: Reviewed

#117 Correction Erreur, Ajout redirection
  src/Controller/AdminProductController.php
Labels: Reviewed

#118 S03 us03 creation listing commande
  public/assets/css/adminStyle.css
  public/assets/css/header.css
  src/View/Admin/_adminNavbar.html.twig
  src/View/Home/index.html.twig
  src/View/Order/index.html.twig
  src/View/adminLayout.html.twig
Labels: Reviewed

#110 S03 us04 page actualite visiteur
  JavoyDb.sql
  public/assets/css/actuality.css
  public/assets/css/style.css
  src/Controller/ActualityController.php
  src/Model/ActualityManager.php
  src/View/Actuality/index.html.twig
Labels: Corrections done, Reviewed

#120 Fix Admin Form
  public/assets/css/add-products.css
  src/View/Admin/_adminProductsForm.html.twig
  src/View/Admin/add.html.twig
  src/View/Admin/edit.html.twig
Labels: Reviewed

#121 Changement logo, ajout lien dans footer, Changement Css
  public/assets/css/footer.css
  public/assets/images/logoBAF.svg
  public/assets/images/logoFB.svg
  public/assets/images/logoVI.svg
  src/View/includes/_footer.html.twig
Labels: Reviewed

#59 S02 us07 fonction delete produit admin
  public/assets/css/adminListProduit.css
  src/Controller/AdminProductController.php
  src/View/Admin/listProduct.html.twig
Labels: Reviewed

#126 Ajout vue actualité
  public/assets/css/actuality.css
  src/Controller/ActualityController.php
  src/View/Actuality/index.html.twig
  src/View/Actuality/showActuality.html.twig
  src/View/includes/_navbar.html.twig
Labels: Reviewed

#129 FIX body margin on style.css
  public/assets/css/style.css
Labels: Reviewed

#125 S03 us06 lister actu admin
  JavoyDb.sql
  src/Controller/AdminActualityController.php
  src/View/Admin/_adminNavbar.html.twig
  src/View/Admin/listActuality.html.twig
Labels: Conflicts

#123 S03 us05 ajout actu
  src/Controller/AdminActualityController.php
  src/Model/ActualityManager.php
  src/View/Admin/addActuality.html.twig
Labels: Reviewed

#128 S03 us02 form contact
  public/assets/css/contact.css
  src/Controller/ContactController.php
  src/Controller/HomeController.php
  src/View/Contact/index.html.twig
  src/View/includes/_formContact.html.twig
  src/View/includes/_navbar.html.twig
Labels: Reviewed

#148 S03 Dev to master
  .gitignore
  JavoyDb.sql
  config/db.php.dist
  public/assets/css/actuality.css
  public/assets/css/add-products.css
  public/assets/css/adminListProduit.css
  public/assets/css/adminStyle.css
  public/assets/css/category.css
  public/assets/css/contact.css
  public/assets/css/footer.css
  public/assets/css/header.css
  public/assets/css/recompense.css
  public/assets/css/style.css
  public/assets/images/coup-de-coeur-guide-hachette-scaled.jpg
  public/assets/images/logo.png
  public/assets/images/logoBAF.svg
  public/assets/images/logoFB.svg
  public/assets/images/logoVI.svg
  public/assets/images/medaille-argent.png
  public/assets/images/medaille-or.png
  public/assets/images/vignes.jpg
  src/Controller/ActualityController.php
  src/Controller/AdminActualityController.php
  src/Controller/AdminListProductController.php
  src/Controller/AdminProductController.php
  src/Controller/CategoryController.php
  src/Controller/ContactController.php
  src/Controller/HomeController.php
  src/Controller/OrderController.php
  src/Model/ActualityManager.php
  src/Model/CategoryManager.php
  src/Model/ListProductManager.php
  src/Model/OrderManager.php
  src/View/Actuality/index.html.twig
  src/View/Actuality/showActuality.html.twig
  src/View/Admin/_adminNavbar.html.twig
  src/View/Admin/_adminProductsForm.html.twig
  src/View/Admin/add.html.twig
  src/View/Admin/addActuality.html.twig
  src/View/Admin/edit.html.twig
  src/View/Admin/listActuality.html.twig
  src/View/Admin/listProduct.html.twig
  src/View/Category/index.html.twig
  src/View/Contact/index.html.twig
  src/View/Home/index.html.twig
  src/View/Item/index.html.twig
  src/View/Order/add.html.twig
  src/View/Order/index.html.twig
  src/View/Order/thanks.html.twig
  src/View/adminLayout.html.twig
  src/View/includes/_footer.html.twig
  src/View/includes/_formContact.html.twig
  src/View/includes/_navbar.html.twig
  src/View/includes/_orderForm.html.twig
  src/View/includes/_recompense.html.twig
Labels: Reviewed

#127 S03 us01 contact plan et horaires
  JavoyDb.sql
  public/assets/css/contact.css
  public/assets/images/phone.png
  public/assets/images/place.png
  public/assets/js/map.js
  src/Controller/AdminProductController.php
  src/Controller/ContactController.php
  src/View/Contact/index.html.twig
  src/View/includes/_navbar.html.twig
  src/View/layout.html.twig
Labels: Reviewed

#146 S03 us03 creation listing commande
  src/Controller/AdminOrderController.php
  src/Model/AdminOrderManager.php
  src/View/Admin/_adminNavbar.html.twig
  src/View/Admin/listOrder.html.twig
  src/View/Order/index.html.twig
  src/View/includes/_history.html.twig
Labels: Corrections done, Reviewed

#147 S03 us15 page savoir faire
  public/assets/css/skill.css
  public/assets/images/skill/Antigel1.jpg
  public/assets/images/skill/Bouchon1.jpg
  public/assets/images/skill/Bouchon2.jpg
  public/assets/images/skill/Bouchon3.jpg
  public/assets/images/skill/Bouchon4.jpg
  public/assets/images/skill/Bouchon5.jpg
  public/assets/images/skill/antigel2.jpg
  public/assets/images/skill/antigel3.jpg
  public/assets/images/skill/antigel4.jpg
  public/assets/images/skill/plantation1.jpg
  public/assets/images/skill/plantation2.jpg
  public/assets/images/skill/plantation3.jpg
  src/Controller/SkillController.php
  src/View/Skill/index.html.twig
  src/View/includes/_history.html.twig
Labels: Reviewed

#150 S03 us16 create admin edit
  src/Controller/AdminActualityController.php
  src/Model/ActualityManager.php
  src/View/Admin/editActuality.html.twig
Labels: Reviewed

#151 S03 us08 suppression actualité admin
  src/Controller/AdminActualityController.php
  src/View/Admin/listActuality.html.twig
Labels: Corrections done, Reviewed

#152 Correction lien, modification Icone réseau sociaux
  public/assets/css/footer.css
  public/assets/images/logoBAF.svg
  public/assets/images/logoBAFNB.png
  public/assets/images/logoFB.png
  public/assets/images/logoFB.svg
  public/assets/images/logoVI.svg
  public/assets/images/logoVINB.png
  src/View/includes/_footer.html.twig
Labels: Reviewed

#154 Fix skill index
  src/View/Skill/index.html.twig
Labels: Reviewed

#155 fix navbar
  src/View/includes/_navbar.html.twig
Labels: Reviewed

#156 Fix css form admin
  public/assets/css/add-products.css
  public/assets/css/adminListProduit.css
  public/assets/css/adminStyle.css
  src/View/Admin/_adminProductsForm.html.twig
  src/View/Admin/addActuality.html.twig
  src/View/Admin/editActuality.html.twig
  src/View/Admin/listActuality.html.twig
  src/View/Admin/listProduct.html.twig
Labels: Reviewed

#158 Fix bug chargement info
  public/assets/css/footer.css
  src/View/Admin/_adminProductsForm.html.twig
  src/View/Admin/addActuality.html.twig
  src/View/Admin/editActuality.html.twig
  src/View/includes/_orderForm.html.twig
Labels: Reviewed
