Repository WildCodeSchool/orleans-php-202103-project-javoy, pull requests merged in 2021-05, with the labels that each got.

#157 Ajout prix dans card produit
  src/View/Admin/listProduct.html.twig
Labels: Reviewed

#172 fix responsive et bandeau du formulaire
  public/assets/css/contact.css
  public/assets/images/wine.png
  src/View/Contact/index.html.twig
  src/View/includes/_formContact.html.twig
Labels: Reviewed

#180 Color primary update admin
  public/assets/css/adminStyle.css
  src/View/Admin/listProduct.html.twig
Labels: Reviewed

#179 S04 us01 uploads form
  src/Controller/AdminActualityController.php
  src/Controller/AdminProductController.php
  src/View/Admin/_adminProductsForm.html.twig
  src/View/Admin/addActuality.html.twig
  src/View/Admin/editActuality.html.twig
Labels: Corrections done, Reviewed

#181 Fix hover footer
  public/assets/css/footer.css
Labels: Reviewed

#177 S04 us14 us15 us17 order
  JavoyDb.sql
  public/assets/css/adminStyle.css
  src/Controller/AdminOrderController.php
  src/Model/AdminOrderManager.php
  src/Model/OrderManager.php
  src/Model/StatusManager.php
  src/View/Admin/listOrder.html.twig
  src/View/Admin/showOrder.html.twig
Labels: Reviewed

#182 Dev to master
  JavoyDb.sql
  public/assets/css/adminStyle.css
  public/assets/css/contact.css
  public/assets/css/footer.css
  public/assets/images/wine.png
  src/Controller/AdminActualityController.php
  src/Controller/AdminOrderController.php
  src/Controller/AdminProductController.php
  src/Model/AdminOrderManager.php
  src/Model/OrderManager.php
  src/Model/StatusManager.php
  src/View/Admin/_adminProductsForm.html.twig
  src/View/Admin/addActuality.html.twig
  src/View/Admin/editActuality.html.twig
  src/View/Admin/listOrder.html.twig
  src/View/Admin/listProduct.html.twig
  src/View/Admin/showOrder.html.twig
  src/View/Contact/index.html.twig
  src/View/includes/_formContact.html.twig
  src/View/includes/_orderForm.html.twig
Labels: Reviewed

#183 Ajout confirmation suppression actu
  .gitignore
  src/View/Admin/listActuality.html.twig
  src/View/Admin/listProduct.html.twig
Labels: Corrections done, Reviewed

#185 S03 us9 produits selon categories
  JavoyDb.sql
  public/assets/css/category.css
  public/assets/css/product.css
  public/assets/images/jus_de_raisin.png
  public/assets/images/jus_de_raisin_blanc.jpg
  public/assets/images/poire_alcool.jpg
  public/assets/images/prune_alcool.jpg
  public/assets/images/vin_blanc.jpg
  public/assets/images/vin_rose.jpg
  public/assets/images/vin_rouge.jpg
  src/Controller/ProductController.php
  src/Model/ProductManager.php
  src/View/Category/index.html.twig
  src/View/Product/index.html.twig
  src/View/Product/show.html.twig
  src/View/includes/_navbar.html.twig
Labels: Corrections done, Reviewed

#190 S04 us12 add panier
  public/assets/css/cart.css
  public/assets/css/history.css
  public/assets/css/style.css
  public/index.php
  src/Controller/CartController.php
  src/View/Cart/index.html.twig
  src/View/includes/_navbar.html.twig
Labels: Reviewed

#189 Dev to master
  .gitignore
  JavoyDb.sql
  public/assets/css/cart.css
  public/assets/css/category.css
  public/assets/css/history.css
  public/assets/css/product.css
  public/assets/css/style.css
  public/assets/images/jus_de_raisin.png
  public/assets/images/jus_de_raisin_blanc.jpg
  public/assets/images/poire_alcool.jpg
  public/assets/images/prune_alcool.jpg
  public/assets/images/vin_blanc.jpg
  public/assets/images/vin_rose.jpg
  public/assets/images/vin_rouge.jpg
  public/index.php
  src/Controller/CartController.php
  src/Controller/ProductController.php
  src/Model/ProductManager.php
  src/View/Actuality/index.html.twig
  src/View/Actuality/showActuality.html.twig
  src/View/Admin/listActuality.html.twig
  src/View/Admin/listProduct.html.twig
  src/View/Cart/index.html.twig
  src/View/Category/index.html.twig
  src/View/Product/index.html.twig
  src/View/Product/show.html.twig
  src/View/includes/_navbar.html.twig
Labels: Reviewed

#187 Ajout scale hover navbar et footer
  public/assets/css/footer.css
  public/assets/css/style.css
  public/assets/images/grape.png
  public/uploads/609253da8d4fa_medaille-bronze.png
  public/uploads/609253fbaff05_medaille-bronze.png
  src/View/layout.html.twig
Labels: Corrections done, Reviewed

#188 Ajout required sur le from de contact
  src/View/includes/_formContact.html.twig
Labels: Reviewed

#217 FIX database
  JavoyDb.sql
Labels: Reviewed

#216 Fix burger navbar
  public/assets/css/style.css
Labels: Reviewed

#218 Fix logo facebook _blank
  src/View/includes/_footer.html.twig
Labels: Reviewed

#221 Fix margin top form commande
  src/View/includes/_orderForm.html.twig
Labels: Reviewed

#222 Fix modification de step pour entrer des nombre décimaux dans le form
  src/View/Admin/_adminProductsForm.html.twig
Labels: Reviewed

#223 Fix changement du chemin de l'image
  public/assets/css/category.css
Labels: Reviewed

#224 US13 panier last version
  src/Controller/CartController.php
  src/View/Cart/index.html.twig
  src/View/Product/show.html.twig
Labels: Reviewed

#225 Fix chargement image
  src/View/Admin/_adminProductsForm.html.twig
  src/View/Admin/editActuality.html.twig
Labels: Corrections done, Reviewed

#229 Dev to master
  JavoyDb.sql
  public/assets/css/category.css
  public/assets/css/footer.css
  public/assets/css/style.css
  public/assets/images/grape.png
  public/uploads/609253da8d4fa_medaille-bronze.png
  public/uploads/609253fbaff05_medaille-bronze.png
  src/Controller/CartController.php
  src/View/Admin/_adminProductsForm.html.twig
  src/View/Admin/editActuality.html.twig
  src/View/Cart/index.html.twig
  src/View/Product/show.html.twig
  src/View/includes/_footer.html.twig
  src/View/includes/_formContact.html.twig
  src/View/includes/_orderForm.html.twig
  src/View/layout.html.twig
Labels: Reviewed

#227 Fix product image
  src/View/Product/index.html.twig
  src/View/Product/show.html.twig
Labels: Reviewed

#230 fix total price cart
  src/View/Cart/index.html.twig
Labels: Reviewed

#191 update Readme
  README.md
Labels: Reviewed

#226 Fix add product
  src/Controller/AdminProductController.php
  src/Model/ProductManager.php
  src/View/Admin/_adminProductsForm.html.twig
Labels: Reviewed

#228 S03 us01 contact plan et horaires
  public/assets/js/map.js
Labels: Reviewed

#232 Changement d'icon coté admin
  src/View/adminLayout.html.twig
Labels: Reviewed

#233 Fix style css and bootstrap card on product part
  public/assets/css/product.css
  src/View/Product/show.html.twig
Labels: Reviewed

#219 Margin top actuality
  src/View/Actuality/index.html.twig
Labels: Corrections done, Reviewed

#220 Fix form contact location
  src/Controller/ContactController.php
  src/View/Contact/index.html.twig
Labels: Conflit résolu, Reviewed

#234 Ajout wave sur footer
  public/assets/css/footer.css
  public/assets/images/wave.svg
  src/View/includes/_footer.html.twig
Labels: Reviewed

#236 Fix skill.css
  public/assets/css/skill.css
Labels: Reviewed

#238 suppression de la verification de description max caractères 255
  src/Controller/AdminProductController.php
Labels: Reviewed

#240 Affichage des image de la page produit
  JavoyDb.sql
  public/assets/css/category.css
  public/assets/images/jus-de-fruit.jpg
  public/assets/images/jus_de_raisin_blanc.jpg
  public/assets/images/rose.jpg
  src/View/Category/index.html.twig
Labels: Reviewed

#242 fix css buttons adminListProduct
  public/assets/css/adminListProduct.css
  public/assets/css/contact.css
  src/View/Admin/listProduct.html.twig
Labels: Reviewed

#243 Fix panier css part
  public/assets/css/cart.css
  src/View/Cart/index.html.twig
Labels: Reviewed

#237 Centrer box thanks
  public/assets/css/style.css
Labels: Reviewed

#235 Dev to master
  JavoyDb.sql
  README.md
  public/assets/css/adminListProduct.css
  public/assets/css/cart.css
  public/assets/css/category.css
  public/assets/css/contact.css
  public/assets/css/footer.css
  public/assets/css/product.css
  public/assets/css/skill.css
  public/assets/css/style.css
  public/assets/images/jus-de-fruit.jpg
  public/assets/images/jus_de_raisin_blanc.jpg
  public/assets/images/rose.jpg
  public/assets/images/wave.svg
  public/assets/js/map.js
  src/Controller/AdminProductController.php
  src/Controller/ContactController.php
  src/Controller/OrderController.php
  src/Model/ProductManager.php
  src/View/Actuality/index.html.twig
  src/View/Admin/_adminProductsForm.html.twig
  src/View/Admin/listProduct.html.twig
  src/View/Admin/showOrder.html.twig
  src/View/Cart/index.html.twig
  src/View/Category/index.html.twig
  src/View/Contact/index.html.twig
  src/View/Product/index.html.twig
  src/View/Product/show.html.twig
  src/View/adminLayout.html.twig
  src/View/includes/_footer.html.twig
  src/View/includes/_orderForm.html.twig
Labels: Reviewed

#247 Suppression alt image produit
  src/View/Admin/_adminProductsForm.html.twig
Labels: Reviewed

#245 fix_h1
  public/assets/css/actuality.css
  public/assets/css/adminStyle.css
  public/assets/css/category.css
  public/assets/css/style.css
  src/View/Admin/listActuality.html.twig
  src/View/Category/index.html.twig
Labels: Reviewed

#246 Retrait des espaces dans le textarea
  src/View/includes/_orderForm.html.twig
Labels: Reviewed

#231 Fix form value
  src/Controller/AdminProductController.php
  src/Controller/ContactController.php
  src/Controller/OrderController.php
  src/View/Admin/_adminProductsForm.html.twig
  src/View/includes/_formContact.html.twig
Labels: Reviewed

#248 Dev to master
  public/assets/css/actuality.css
  public/assets/css/adminStyle.css
  public/assets/css/category.css
  public/assets/css/style.css
  src/Controller/AdminProductController.php
  src/Controller/ContactController.php
  src/Controller/OrderController.php
  src/View/Admin/_adminProductsForm.html.twig
  src/View/Admin/listActuality.html.twig
  src/View/Category/index.html.twig
  src/View/includes/_formContact.html.twig
  src/View/includes/_orderForm.html.twig
Labels: Reviewed
